<header>
	<a href="index.php">Home</a>
	<h1>Lista de personas</h1>
</header>
<form action="index.php?accion=edit&id=<?php echo $_GET['id'] ?>" method="post">
	<table>
		<tr>
			<td><label for="Per_Nombre">Nombre:</label></td>
			<td><input type="text" name="Per_Nombre" id="Per_Nombre" autocomplete="off" autofocus></td>
		</tr>
		<tr>
			<td><label for="Per_Apellido">Apellido:</label></td>
			<td><input type="text" name="Per_Apellido" id="Per_Apellido" autocomplete="off"></td>
		</tr>
		<tr>
			<td><label for="Per_Edad">Edad:</label></td>
			<td><input type="text" name="Per_Edad" id="Per_Edad" autocomplete="off"></td>
		</tr>
		<tr>
			<td><label for="Per_Genero">Genero:</label></td>
			<td><input type="text" name="Per_Genero" id="Per_Genero" autocomplete="off"></td>
		</tr>
		<tr>
			<td><label for="Per_Correo">Correo:</label></td>
			<td><input type="text" name="Per_Correo" id="Per_Correo" autocomplete="off"></td>
		</tr>
	</table>
	<div class="botones">
		<td><input type="submit" name="btnActualizar" id="btnActualizar" value="Actualizar"></td>
		<input type="reset" name="btnReset" id="btnReset">
	</div>
</form>